### ISSUE TITLE
Xposed module needs updating for Marshmallow

### ISSUE THREAD

**Issue by NHellFire** [schwabe/ics-openvpn#484]
Just updated my phone to Marshmallow and found the module no longer works, it did however work perfectly on Lollipop (5.0).

Log:
`
05-07 23:26:55.868 I/Xposed  (23606): Got VPN Dialog
05-07 23:26:56.078 E/Xposed  (23606): java.lang.NoSuchMethodError: android.net.IConnectivityManager$Stub$Proxy#prepareVpn(java.lang.String,java.lang.String)#bestmatch
05-07 23:26:56.078 E/Xposed  (23606):   at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:438)
05-07 23:26:56.078 E/Xposed  (23606):   at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:470)
05-07 23:26:56.078 E/Xposed  (23606):   at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1240)
05-07 23:26:56.078 E/Xposed  (23606):   at de.blinkt.vpndialogxposed.VpnDialogPatcher$1.afterHookedMethod(VpnDialogPatcher.java:67)
05-07 23:26:56.078 E/Xposed  (23606):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:751)
05-07 23:26:56.078 E/Xposed  (23606):   at com.android.vpndialogs.ConfirmDialog.onResume(<Xposed>)
05-07 23:26:56.078 E/Xposed  (23606):   at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1286)
05-07 23:26:56.078 E/Xposed  (23606):   at android.app.Activity.performResume(Activity.java:6987)
05-07 23:26:56.078 E/Xposed  (23606):   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4145)
05-07 23:26:56.078 E/Xposed  (23606):   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4250)
05-07 23:26:56.078 E/Xposed  (23606):   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3361)
05-07 23:26:56.078 E/Xposed  (23606):   at android.app.ActivityThread.access$1100(ActivityThread.java:222)
05-07 23:26:56.078 E/Xposed  (23606):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
05-07 23:26:56.078 E/Xposed  (23606):   at android.os.Handler.dispatchMessage(Handler.java:102)
05-07 23:26:56.078 E/Xposed  (23606):   at android.os.Looper.loop(Looper.java:158)
05-07 23:26:56.078 E/Xposed  (23606):   at android.app.ActivityThread.main(ActivityThread.java:7229)
05-07 23:26:56.078 E/Xposed  (23606):   at java.lang.reflect.Method.invoke(Native Method)
05-07 23:26:56.078 E/Xposed  (23606):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
05-07 23:26:56.078 E/Xposed  (23606):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
05-07 23:26:56.078 E/Xposed  (23606):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
`

**Comment by schwabe** [comment]
The xposed module is not needed for Android 5.0+ anymore.

**Comment by NHellFire** [comment]
Yes, it is. Not every rom has a "Trust this app" box. Mine didn't on 5.0 and still doesn't on 6.0.

**Comment by NHellFire** [comment]
![2016-05-08 00 28 29](https://cloud.githubusercontent.com/assets/1146987/15095213/4a309332-14b4-11e6-8cca-e21b9c6168c7.jpg)
Screenshot just now, on 6.0.

**Comment by schwabe** [comment]
@NHellFire the reason for the xposed mod was that the vpn allowance is now saved after reboots etc. there is simply no need for the mod anymore.

**Comment by NHellFire** [comment]
It isn't saved after reboots on mine. I have to accept it every time after
a reboot. So yes, it is still needed with some roms.

**Comment by schwabe** [comment]
@NHellFire Your ROM is very strange then. They must have patched that out of Android again.

Anyway. I have never seen such a broken ROM, so I have no way to develop that module for 5.0+

**Comment by NHellFire** [comment]
Well, it was some change in either 5.1 or 6.0 that stopped it working (5.0
worked perfectly) and I can provide any info/files you need and also test
it.

**Comment by schwabe** [comment]
Yes the change that made the whole module obsolete.The module was always written to work on most phone.

And on most phones it not need on 5.0+ anymore. So it is not maintained anymore. I have no interest in fixing some bizzare ROMs. Even for older ROMs I did not use the module myself.

P.S.: What bizzare ROM are you using?
